[package]
name = "itty-pro"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
app_internal = []
app_external = []

[dependencies]
anyhow = "1.0.94"
async-trait = "0.1.83"
axum = { version = "0.7.9", features = ["http2"] }
axum-extra = { version = "0.9.6", features = ["typed-header"] }
axum-login = "0.16.0"
chrono = { version = "0.4.38", features = ["serde"] }
hyper = { version = "1.5.1", features = ["full"] }
hyper-util = { version = "0.1.10", features = ["full"] }
include_dir = "0.7.4"
mime = "0.3.17"
mime_guess = "2.0.5"
nanoid = "0.4.0"
password-auth = "1.0.0"
reqwest = "0.12.9"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
sqlx = { version = "0.8.2", features = ["chrono", "runtime-tokio", "sqlite", "uuid"] }
tokio = { version = "1.42.0", features = ["full"] }
tokio-rustls = "0.26.1"
tower-http = { version = "0.6.2", features = ["trace"] }
tower-service = "0.3.3"
tower-sessions = "0.13.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
url = { version = "2.5.4", features = ["serde"] }
utoipa = { version = "5.2.0", features = ["axum_extras", "url"] }
uuid = { version = "1.11.0", features = ["serde", "v7"] }
